
package kookmin.game.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserManager", targetNamespace = "http://service.game/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserManager {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "removeUser", targetNamespace = "http://service.game/", className = "kookmin.game.server.RemoveUser")
    @ResponseWrapper(localName = "removeUserResponse", targetNamespace = "http://service.game/", className = "kookmin.game.server.RemoveUserResponse")
    @Action(input = "http://service.game/UserManager/removeUserRequest", output = "http://service.game/UserManager/removeUserResponse")
    public void removeUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setUser", targetNamespace = "http://service.game/", className = "kookmin.game.server.SetUser")
    @ResponseWrapper(localName = "setUserResponse", targetNamespace = "http://service.game/", className = "kookmin.game.server.SetUserResponse")
    @Action(input = "http://service.game/UserManager/setUserRequest", output = "http://service.game/UserManager/setUserResponse")
    public void setUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://service.game/", className = "kookmin.game.server.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://service.game/", className = "kookmin.game.server.GetUserResponse")
    @Action(input = "http://service.game/UserManager/getUserRequest", output = "http://service.game/UserManager/getUserResponse")
    public String getUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
